/**
 * QVAC SDK Worker Entry (auto-generated)
 * Generated by: npx qvac bundle sdk
 * Plugins: 4
 *
*   - @qvac/sdk/llamacpp-completion/plugin
*   - @qvac/sdk/llamacpp-embedding/plugin
*   - @qvac/sdk/onnx-tts/plugin
*   - @qvac/sdk/whispercpp-transcription/plugin
 */

import { initializeWorkerCore, ensureRPCSetup } from "@qvac/sdk/worker-core";
import { registerPlugin } from "@qvac/sdk/plugins";
import { getServerLogger } from "@qvac/sdk/logging";

import { llmPlugin } from "@qvac/sdk/llamacpp-completion/plugin";
import { embeddingsPlugin } from "@qvac/sdk/llamacpp-embedding/plugin";
import { ttsPlugin } from "@qvac/sdk/onnx-tts/plugin";
import { whisperPlugin } from "@qvac/sdk/whispercpp-transcription/plugin";

const { hasRPCConfig } = initializeWorkerCore();

const logger = getServerLogger();
logger.info("🐻 QVAC Worker (custom bundle)");
logger.info("📦 Plugins: 4");

registerPlugin(llmPlugin);
registerPlugin(embeddingsPlugin);
registerPlugin(ttsPlugin);
registerPlugin(whisperPlugin);

// Auto-setup RPC if config present
if (hasRPCConfig) {
  ensureRPCSetup();
}
